- platform: yeelight
  devices:
    192.168.1.58:
      name: Table Lamp
      transition: 1000
      model: color1
      # use_music_mode: True
      save_on_change: False
    192.168.1.53:
      name: Bedroom Main
      transition: 1000
      model: color2
      save_on_change: False
    192.168.1.54:
      name: Kitchen Main
      transition: 1000
      model: color2
      save_on_change: False
    192.168.1.59:
      name: Floor Lamp
      transition: 1000
      model: color2
      save_on_change: False
# - platform: group
#   name: Bathroom Lights
#   entities:
#     - light.tradfri_bulb_e14_ws_opal_400lm_2
#     - light.tradfri_bulb_e14_ws_opal_400lm
- platform: group
  name: Bedroom Lights
  entities:
    - light.bedroom_main
    - light.floor_lamp
- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen_main
    - light.gateway_light_7811dcf984c9
    - light.table_lamp