- platform: group
  name: Bathroom Lights
  entities:
    - light.tradfri_bulb_e14_ws_opal_400lm_2
    - light.tradfri_bulb_e14_ws_opal_400lm
- platform: group
  name: Bedroom Lights
  entities:
    - light.bedroom_main
    - light.floor_lamp
- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen_main
    - light.gateway_light_7811dcf984c9
    - light.table_lamp
